server:
  port: 3301

spring:
  application:
    name: config-server
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/gejt/my-cloud-config
          username: gejt
          password: maths402.
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaulZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}