server:
  port: 8081

db:
  mysql:
    host: 192.168.111.20
    port: 3306
    dbname: test
    username: root
    password: 123456

# 配置数据源
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url:  jdbc:mysql://${db.mysql.host}:${db.mysql.port}/${db.mysql.dbname}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: ${db.mysql.username}
      password: ${db.mysql.password}
# mybatis 配置
mybatis:
  type-aliases-package: com.zao123.orderservice.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml